// Code generated by protoc-gen-go. DO NOT EDIT.
// source: css.proto

package css

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DPState_State int32

const (
	DPState_UNDEFINED         DPState_State = 0
	DPState_REQUESTING_FORK   DPState_State = 1
	DPState_HOLDING_FORK      DPState_State = 2
	DPState_RELEASING_FORK    DPState_State = 3
	DPState_HUNGRY            DPState_State = 4
	DPState_EATING            DPState_State = 5
	DPState_THINKING          DPState_State = 6
	DPState_GRACEFULLY_EXITED DPState_State = 7
	DPState_DEADLOCKED        DPState_State = 8
)

var DPState_State_name = map[int32]string{
	0: "UNDEFINED",
	1: "REQUESTING_FORK",
	2: "HOLDING_FORK",
	3: "RELEASING_FORK",
	4: "HUNGRY",
	5: "EATING",
	6: "THINKING",
	7: "GRACEFULLY_EXITED",
	8: "DEADLOCKED",
}

var DPState_State_value = map[string]int32{
	"UNDEFINED":         0,
	"REQUESTING_FORK":   1,
	"HOLDING_FORK":      2,
	"RELEASING_FORK":    3,
	"HUNGRY":            4,
	"EATING":            5,
	"THINKING":          6,
	"GRACEFULLY_EXITED": 7,
	"DEADLOCKED":        8,
}

func (x DPState_State) String() string {
	return proto.EnumName(DPState_State_name, int32(x))
}

func (DPState_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{0, 0}
}

type RWOptions_Solution int32

const (
	RWOptions_UNSPECIFIED         RWOptions_Solution = 0
	RWOptions_FIRST_STARVATION    RWOptions_Solution = 1
	RWOptions_NO_STARVE_TURNSTILE RWOptions_Solution = 2
	RWOptions_WRITER_PRIORITY     RWOptions_Solution = 3
)

var RWOptions_Solution_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "FIRST_STARVATION",
	2: "NO_STARVE_TURNSTILE",
	3: "WRITER_PRIORITY",
}

var RWOptions_Solution_value = map[string]int32{
	"UNSPECIFIED":         0,
	"FIRST_STARVATION":    1,
	"NO_STARVE_TURNSTILE": 2,
	"WRITER_PRIORITY":     3,
}

func (x RWOptions_Solution) String() string {
	return proto.EnumName(RWOptions_Solution_name, int32(x))
}

func (RWOptions_Solution) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{4, 0}
}

type RWState_State int32

const (
	RWState_UNDEFINED              RWState_State = 0
	RWState_READING                RWState_State = 1
	RWState_WRITING                RWState_State = 2
	RWState_WAITING_FOR_MUTEX      RWState_State = 3
	RWState_ACQUIRED_MUTEX         RWState_State = 4
	RWState_RELEASED_MUTEX         RWState_State = 5
	RWState_WAITING_FOR_ROOM_EMPTY RWState_State = 6
	RWState_RECEIVED_ROOM_EMPTY    RWState_State = 7
	RWState_SIGNAL_ROOM_EMPTY      RWState_State = 8
	RWState_WAITING_FOR_TURNSTILE  RWState_State = 9
	RWState_THROUGH_TURNSTILE      RWState_State = 10
	RWState_ENTER_READ_SWITCH      RWState_State = 11
	RWState_LEAVE_READ_SWITCH      RWState_State = 12
	RWState_ENTER_WRITE_SWITCH     RWState_State = 13
	RWState_LEAVE_WRITE_SWITCH     RWState_State = 14
	RWState_WAITING_FOR_NO_READERS RWState_State = 15
	RWState_WAITING_FOR_NO_WRITERS RWState_State = 16
	RWState_SIGNAL_NO_READERS      RWState_State = 17
	RWState_SIGNAL_NO_WRITERS      RWState_State = 18
	RWState_RECEIVED_NO_READERS    RWState_State = 19
	RWState_RECEIVED_NO_WRITERS    RWState_State = 20
	RWState_END_ACTION             RWState_State = 21
	RWState_WAIT_ACTION            RWState_State = 22
)

var RWState_State_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "READING",
	2:  "WRITING",
	3:  "WAITING_FOR_MUTEX",
	4:  "ACQUIRED_MUTEX",
	5:  "RELEASED_MUTEX",
	6:  "WAITING_FOR_ROOM_EMPTY",
	7:  "RECEIVED_ROOM_EMPTY",
	8:  "SIGNAL_ROOM_EMPTY",
	9:  "WAITING_FOR_TURNSTILE",
	10: "THROUGH_TURNSTILE",
	11: "ENTER_READ_SWITCH",
	12: "LEAVE_READ_SWITCH",
	13: "ENTER_WRITE_SWITCH",
	14: "LEAVE_WRITE_SWITCH",
	15: "WAITING_FOR_NO_READERS",
	16: "WAITING_FOR_NO_WRITERS",
	17: "SIGNAL_NO_READERS",
	18: "SIGNAL_NO_WRITERS",
	19: "RECEIVED_NO_READERS",
	20: "RECEIVED_NO_WRITERS",
	21: "END_ACTION",
	22: "WAIT_ACTION",
}

var RWState_State_value = map[string]int32{
	"UNDEFINED":              0,
	"READING":                1,
	"WRITING":                2,
	"WAITING_FOR_MUTEX":      3,
	"ACQUIRED_MUTEX":         4,
	"RELEASED_MUTEX":         5,
	"WAITING_FOR_ROOM_EMPTY": 6,
	"RECEIVED_ROOM_EMPTY":    7,
	"SIGNAL_ROOM_EMPTY":      8,
	"WAITING_FOR_TURNSTILE":  9,
	"THROUGH_TURNSTILE":      10,
	"ENTER_READ_SWITCH":      11,
	"LEAVE_READ_SWITCH":      12,
	"ENTER_WRITE_SWITCH":     13,
	"LEAVE_WRITE_SWITCH":     14,
	"WAITING_FOR_NO_READERS": 15,
	"WAITING_FOR_NO_WRITERS": 16,
	"SIGNAL_NO_READERS":      17,
	"SIGNAL_NO_WRITERS":      18,
	"RECEIVED_NO_READERS":    19,
	"RECEIVED_NO_WRITERS":    20,
	"END_ACTION":             21,
	"WAIT_ACTION":            22,
}

func (x RWState_State) String() string {
	return proto.EnumName(RWState_State_name, int32(x))
}

func (RWState_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{5, 0}
}

type BufferState_State int32

const (
	BufferState_UNDEFINED       BufferState_State = 0
	BufferState_PRODUCED_ITEM   BufferState_State = 1
	BufferState_CONSUMED_ITEM   BufferState_State = 2
	BufferState_PRODUCING_ITEM  BufferState_State = 3
	BufferState_CONSUMING_ITEM  BufferState_State = 4
	BufferState_WAIT_FOR_BUFFER BufferState_State = 5
	BufferState_IDLE            BufferState_State = 6
)

var BufferState_State_name = map[int32]string{
	0: "UNDEFINED",
	1: "PRODUCED_ITEM",
	2: "CONSUMED_ITEM",
	3: "PRODUCING_ITEM",
	4: "CONSUMING_ITEM",
	5: "WAIT_FOR_BUFFER",
	6: "IDLE",
}

var BufferState_State_value = map[string]int32{
	"UNDEFINED":       0,
	"PRODUCED_ITEM":   1,
	"CONSUMED_ITEM":   2,
	"PRODUCING_ITEM":  3,
	"CONSUMING_ITEM":  4,
	"WAIT_FOR_BUFFER": 5,
	"IDLE":            6,
}

func (x BufferState_State) String() string {
	return proto.EnumName(BufferState_State_name, int32(x))
}

func (BufferState_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{14, 0}
}

type ModusState_State int32

const (
	ModusState_UNDEFINED              ModusState_State = 0
	ModusState_NEUTRAL                ModusState_State = 1
	ModusState_HEATHENS_RULE          ModusState_State = 2
	ModusState_PRUDES_RULE            ModusState_State = 3
	ModusState_TRANSITION_TO_HEATHENS ModusState_State = 4
	ModusState_TRANSITION_TO_PRUDES   ModusState_State = 5
	ModusState_WAITING_TO_CROSS       ModusState_State = 6
	ModusState_CROSSING               ModusState_State = 7
)

var ModusState_State_name = map[int32]string{
	0: "UNDEFINED",
	1: "NEUTRAL",
	2: "HEATHENS_RULE",
	3: "PRUDES_RULE",
	4: "TRANSITION_TO_HEATHENS",
	5: "TRANSITION_TO_PRUDES",
	6: "WAITING_TO_CROSS",
	7: "CROSSING",
}

var ModusState_State_value = map[string]int32{
	"UNDEFINED":              0,
	"NEUTRAL":                1,
	"HEATHENS_RULE":          2,
	"PRUDES_RULE":            3,
	"TRANSITION_TO_HEATHENS": 4,
	"TRANSITION_TO_PRUDES":   5,
	"WAITING_TO_CROSS":       6,
	"CROSSING":               7,
}

func (x ModusState_State) String() string {
	return proto.EnumName(ModusState_State_name, int32(x))
}

func (ModusState_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{16, 0}
}

type UnisexOptions_Solution int32

const (
	UnisexOptions_UNDEFINED UnisexOptions_Solution = 0
	UnisexOptions_FIRST     UnisexOptions_Solution = 1
	UnisexOptions_NO_STARVE UnisexOptions_Solution = 2
)

var UnisexOptions_Solution_name = map[int32]string{
	0: "UNDEFINED",
	1: "FIRST",
	2: "NO_STARVE",
}

var UnisexOptions_Solution_value = map[string]int32{
	"UNDEFINED": 0,
	"FIRST":     1,
	"NO_STARVE": 2,
}

func (x UnisexOptions_Solution) String() string {
	return proto.EnumName(UnisexOptions_Solution_name, int32(x))
}

func (UnisexOptions_Solution) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{17, 0}
}

type UnisexState_State int32

const (
	UnisexState_UNDEFINED         UnisexState_State = 0
	UnisexState_QUEUING           UnisexState_State = 1
	UnisexState_ENTERING          UnisexState_State = 2
	UnisexState_LEAVING           UnisexState_State = 3
	UnisexState_SIGNAL_EMPTY      UnisexState_State = 4
	UnisexState_MALE_SWITCH_ON    UnisexState_State = 5
	UnisexState_MALE_SWITCH_OFF   UnisexState_State = 6
	UnisexState_FEMALE_SWITCH_ON  UnisexState_State = 7
	UnisexState_FEMALE_SWITCH_OFF UnisexState_State = 8
)

var UnisexState_State_name = map[int32]string{
	0: "UNDEFINED",
	1: "QUEUING",
	2: "ENTERING",
	3: "LEAVING",
	4: "SIGNAL_EMPTY",
	5: "MALE_SWITCH_ON",
	6: "MALE_SWITCH_OFF",
	7: "FEMALE_SWITCH_ON",
	8: "FEMALE_SWITCH_OFF",
}

var UnisexState_State_value = map[string]int32{
	"UNDEFINED":         0,
	"QUEUING":           1,
	"ENTERING":          2,
	"LEAVING":           3,
	"SIGNAL_EMPTY":      4,
	"MALE_SWITCH_ON":    5,
	"MALE_SWITCH_OFF":   6,
	"FEMALE_SWITCH_ON":  7,
	"FEMALE_SWITCH_OFF": 8,
}

func (x UnisexState_State) String() string {
	return proto.EnumName(UnisexState_State_name, int32(x))
}

func (UnisexState_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{18, 0}
}

type DPState struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State                DPState_State `protobuf:"varint,2,opt,name=state,proto3,enum=DPState_State" json:"state,omitempty"`
	ForkId               int32         `protobuf:"varint,3,opt,name=fork_id,json=forkId,proto3" json:"fork_id,omitempty"`
	Time                 int64         `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DPState) Reset()         { *m = DPState{} }
func (m *DPState) String() string { return proto.CompactTextString(m) }
func (*DPState) ProtoMessage()    {}
func (*DPState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{0}
}

func (m *DPState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DPState.Unmarshal(m, b)
}
func (m *DPState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DPState.Marshal(b, m, deterministic)
}
func (m *DPState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DPState.Merge(m, src)
}
func (m *DPState) XXX_Size() int {
	return xxx_messageInfo_DPState.Size(m)
}
func (m *DPState) XXX_DiscardUnknown() {
	xxx_messageInfo_DPState.DiscardUnknown(m)
}

var xxx_messageInfo_DPState proto.InternalMessageInfo

func (m *DPState) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DPState) GetState() DPState_State {
	if m != nil {
		return m.State
	}
	return DPState_UNDEFINED
}

func (m *DPState) GetForkId() int32 {
	if m != nil {
		return m.ForkId
	}
	return 0
}

func (m *DPState) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type DPOptions struct {
	Choice               int32     `protobuf:"varint,1,opt,name=choice,proto3" json:"choice,omitempty"`
	Duration             int64     `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Size                 int32     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	TimeThinking         int64     `protobuf:"varint,4,opt,name=time_thinking,json=timeThinking,proto3" json:"time_thinking,omitempty"`
	TimeEating           int64     `protobuf:"varint,5,opt,name=time_eating,json=timeEating,proto3" json:"time_eating,omitempty"`
	Variation            int64     `protobuf:"varint,6,opt,name=variation,proto3" json:"variation,omitempty"`
	SaveCode             *SaveCode `protobuf:"bytes,7,opt,name=save_code,json=saveCode,proto3" json:"save_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DPOptions) Reset()         { *m = DPOptions{} }
func (m *DPOptions) String() string { return proto.CompactTextString(m) }
func (*DPOptions) ProtoMessage()    {}
func (*DPOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{1}
}

func (m *DPOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DPOptions.Unmarshal(m, b)
}
func (m *DPOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DPOptions.Marshal(b, m, deterministic)
}
func (m *DPOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DPOptions.Merge(m, src)
}
func (m *DPOptions) XXX_Size() int {
	return xxx_messageInfo_DPOptions.Size(m)
}
func (m *DPOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_DPOptions.DiscardUnknown(m)
}

var xxx_messageInfo_DPOptions proto.InternalMessageInfo

func (m *DPOptions) GetChoice() int32 {
	if m != nil {
		return m.Choice
	}
	return 0
}

func (m *DPOptions) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *DPOptions) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *DPOptions) GetTimeThinking() int64 {
	if m != nil {
		return m.TimeThinking
	}
	return 0
}

func (m *DPOptions) GetTimeEating() int64 {
	if m != nil {
		return m.TimeEating
	}
	return 0
}

func (m *DPOptions) GetVariation() int64 {
	if m != nil {
		return m.Variation
	}
	return 0
}

func (m *DPOptions) GetSaveCode() *SaveCode {
	if m != nil {
		return m.SaveCode
	}
	return nil
}

type DPRun struct {
	Timestamp            int64      `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Options              *DPOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Deadlocked           bool       `protobuf:"varint,3,opt,name=deadlocked,proto3" json:"deadlocked,omitempty"`
	Stats                []*DPStat  `protobuf:"bytes,4,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DPRun) Reset()         { *m = DPRun{} }
func (m *DPRun) String() string { return proto.CompactTextString(m) }
func (*DPRun) ProtoMessage()    {}
func (*DPRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{2}
}

func (m *DPRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DPRun.Unmarshal(m, b)
}
func (m *DPRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DPRun.Marshal(b, m, deterministic)
}
func (m *DPRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DPRun.Merge(m, src)
}
func (m *DPRun) XXX_Size() int {
	return xxx_messageInfo_DPRun.Size(m)
}
func (m *DPRun) XXX_DiscardUnknown() {
	xxx_messageInfo_DPRun.DiscardUnknown(m)
}

var xxx_messageInfo_DPRun proto.InternalMessageInfo

func (m *DPRun) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DPRun) GetOptions() *DPOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *DPRun) GetDeadlocked() bool {
	if m != nil {
		return m.Deadlocked
	}
	return false
}

func (m *DPRun) GetStats() []*DPStat {
	if m != nil {
		return m.Stats
	}
	return nil
}

type DPStat struct {
	PhilosopherNumber    int32    `protobuf:"varint,1,opt,name=philosopher_number,json=philosopherNumber,proto3" json:"philosopher_number,omitempty"`
	MaxHungry            int64    `protobuf:"varint,2,opt,name=max_hungry,json=maxHungry,proto3" json:"max_hungry,omitempty"`
	MaxEating            int64    `protobuf:"varint,3,opt,name=max_eating,json=maxEating,proto3" json:"max_eating,omitempty"`
	MaxThinking          int64    `protobuf:"varint,4,opt,name=max_thinking,json=maxThinking,proto3" json:"max_thinking,omitempty"`
	MinHungry            int64    `protobuf:"varint,5,opt,name=min_hungry,json=minHungry,proto3" json:"min_hungry,omitempty"`
	MinEating            int64    `protobuf:"varint,6,opt,name=min_eating,json=minEating,proto3" json:"min_eating,omitempty"`
	MinThinking          int64    `protobuf:"varint,7,opt,name=min_thinking,json=minThinking,proto3" json:"min_thinking,omitempty"`
	TotalHungry          int64    `protobuf:"varint,8,opt,name=total_hungry,json=totalHungry,proto3" json:"total_hungry,omitempty"`
	TotalEating          int64    `protobuf:"varint,9,opt,name=total_eating,json=totalEating,proto3" json:"total_eating,omitempty"`
	TotalThinking        int64    `protobuf:"varint,10,opt,name=total_thinking,json=totalThinking,proto3" json:"total_thinking,omitempty"`
	Cycles               int32    `protobuf:"varint,11,opt,name=cycles,proto3" json:"cycles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DPStat) Reset()         { *m = DPStat{} }
func (m *DPStat) String() string { return proto.CompactTextString(m) }
func (*DPStat) ProtoMessage()    {}
func (*DPStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{3}
}

func (m *DPStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DPStat.Unmarshal(m, b)
}
func (m *DPStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DPStat.Marshal(b, m, deterministic)
}
func (m *DPStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DPStat.Merge(m, src)
}
func (m *DPStat) XXX_Size() int {
	return xxx_messageInfo_DPStat.Size(m)
}
func (m *DPStat) XXX_DiscardUnknown() {
	xxx_messageInfo_DPStat.DiscardUnknown(m)
}

var xxx_messageInfo_DPStat proto.InternalMessageInfo

func (m *DPStat) GetPhilosopherNumber() int32 {
	if m != nil {
		return m.PhilosopherNumber
	}
	return 0
}

func (m *DPStat) GetMaxHungry() int64 {
	if m != nil {
		return m.MaxHungry
	}
	return 0
}

func (m *DPStat) GetMaxEating() int64 {
	if m != nil {
		return m.MaxEating
	}
	return 0
}

func (m *DPStat) GetMaxThinking() int64 {
	if m != nil {
		return m.MaxThinking
	}
	return 0
}

func (m *DPStat) GetMinHungry() int64 {
	if m != nil {
		return m.MinHungry
	}
	return 0
}

func (m *DPStat) GetMinEating() int64 {
	if m != nil {
		return m.MinEating
	}
	return 0
}

func (m *DPStat) GetMinThinking() int64 {
	if m != nil {
		return m.MinThinking
	}
	return 0
}

func (m *DPStat) GetTotalHungry() int64 {
	if m != nil {
		return m.TotalHungry
	}
	return 0
}

func (m *DPStat) GetTotalEating() int64 {
	if m != nil {
		return m.TotalEating
	}
	return 0
}

func (m *DPStat) GetTotalThinking() int64 {
	if m != nil {
		return m.TotalThinking
	}
	return 0
}

func (m *DPStat) GetCycles() int32 {
	if m != nil {
		return m.Cycles
	}
	return 0
}

type RWOptions struct {
	NumReaders           int32              `protobuf:"varint,1,opt,name=num_readers,json=numReaders,proto3" json:"num_readers,omitempty"`
	NumWriters           int32              `protobuf:"varint,2,opt,name=num_writers,json=numWriters,proto3" json:"num_writers,omitempty"`
	Solution             RWOptions_Solution `protobuf:"varint,3,opt,name=solution,proto3,enum=RWOptions_Solution" json:"solution,omitempty"`
	Duration             int64              `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	ReadDuration         int64              `protobuf:"varint,5,opt,name=read_duration,json=readDuration,proto3" json:"read_duration,omitempty"`
	WriteDuration        int64              `protobuf:"varint,6,opt,name=write_duration,json=writeDuration,proto3" json:"write_duration,omitempty"`
	Variation            int64              `protobuf:"varint,7,opt,name=variation,proto3" json:"variation,omitempty"`
	ReadSleep            int64              `protobuf:"varint,8,opt,name=read_sleep,json=readSleep,proto3" json:"read_sleep,omitempty"`
	WriteSleep           int64              `protobuf:"varint,9,opt,name=write_sleep,json=writeSleep,proto3" json:"write_sleep,omitempty"`
	SaveCode             *SaveCode          `protobuf:"bytes,10,opt,name=save_code,json=saveCode,proto3" json:"save_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RWOptions) Reset()         { *m = RWOptions{} }
func (m *RWOptions) String() string { return proto.CompactTextString(m) }
func (*RWOptions) ProtoMessage()    {}
func (*RWOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{4}
}

func (m *RWOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RWOptions.Unmarshal(m, b)
}
func (m *RWOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RWOptions.Marshal(b, m, deterministic)
}
func (m *RWOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RWOptions.Merge(m, src)
}
func (m *RWOptions) XXX_Size() int {
	return xxx_messageInfo_RWOptions.Size(m)
}
func (m *RWOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_RWOptions.DiscardUnknown(m)
}

var xxx_messageInfo_RWOptions proto.InternalMessageInfo

func (m *RWOptions) GetNumReaders() int32 {
	if m != nil {
		return m.NumReaders
	}
	return 0
}

func (m *RWOptions) GetNumWriters() int32 {
	if m != nil {
		return m.NumWriters
	}
	return 0
}

func (m *RWOptions) GetSolution() RWOptions_Solution {
	if m != nil {
		return m.Solution
	}
	return RWOptions_UNSPECIFIED
}

func (m *RWOptions) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *RWOptions) GetReadDuration() int64 {
	if m != nil {
		return m.ReadDuration
	}
	return 0
}

func (m *RWOptions) GetWriteDuration() int64 {
	if m != nil {
		return m.WriteDuration
	}
	return 0
}

func (m *RWOptions) GetVariation() int64 {
	if m != nil {
		return m.Variation
	}
	return 0
}

func (m *RWOptions) GetReadSleep() int64 {
	if m != nil {
		return m.ReadSleep
	}
	return 0
}

func (m *RWOptions) GetWriteSleep() int64 {
	if m != nil {
		return m.WriteSleep
	}
	return 0
}

func (m *RWOptions) GetSaveCode() *SaveCode {
	if m != nil {
		return m.SaveCode
	}
	return nil
}

type RWState struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time                 int64         `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	State                RWState_State `protobuf:"varint,3,opt,name=state,proto3,enum=RWState_State" json:"state,omitempty"`
	Actor                string        `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RWState) Reset()         { *m = RWState{} }
func (m *RWState) String() string { return proto.CompactTextString(m) }
func (*RWState) ProtoMessage()    {}
func (*RWState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{5}
}

func (m *RWState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RWState.Unmarshal(m, b)
}
func (m *RWState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RWState.Marshal(b, m, deterministic)
}
func (m *RWState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RWState.Merge(m, src)
}
func (m *RWState) XXX_Size() int {
	return xxx_messageInfo_RWState.Size(m)
}
func (m *RWState) XXX_DiscardUnknown() {
	xxx_messageInfo_RWState.DiscardUnknown(m)
}

var xxx_messageInfo_RWState proto.InternalMessageInfo

func (m *RWState) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RWState) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *RWState) GetState() RWState_State {
	if m != nil {
		return m.State
	}
	return RWState_UNDEFINED
}

func (m *RWState) GetActor() string {
	if m != nil {
		return m.Actor
	}
	return ""
}

type RWStats struct {
	RwRuns               []*RWRun `protobuf:"bytes,1,rep,name=rw_runs,json=rwRuns,proto3" json:"rw_runs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RWStats) Reset()         { *m = RWStats{} }
func (m *RWStats) String() string { return proto.CompactTextString(m) }
func (*RWStats) ProtoMessage()    {}
func (*RWStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{6}
}

func (m *RWStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RWStats.Unmarshal(m, b)
}
func (m *RWStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RWStats.Marshal(b, m, deterministic)
}
func (m *RWStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RWStats.Merge(m, src)
}
func (m *RWStats) XXX_Size() int {
	return xxx_messageInfo_RWStats.Size(m)
}
func (m *RWStats) XXX_DiscardUnknown() {
	xxx_messageInfo_RWStats.DiscardUnknown(m)
}

var xxx_messageInfo_RWStats proto.InternalMessageInfo

func (m *RWStats) GetRwRuns() []*RWRun {
	if m != nil {
		return m.RwRuns
	}
	return nil
}

type RWRun struct {
	Timestamp            int64        `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Options              *RWOptions   `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Stats                []*RWRunStat `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RWRun) Reset()         { *m = RWRun{} }
func (m *RWRun) String() string { return proto.CompactTextString(m) }
func (*RWRun) ProtoMessage()    {}
func (*RWRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{7}
}

func (m *RWRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RWRun.Unmarshal(m, b)
}
func (m *RWRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RWRun.Marshal(b, m, deterministic)
}
func (m *RWRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RWRun.Merge(m, src)
}
func (m *RWRun) XXX_Size() int {
	return xxx_messageInfo_RWRun.Size(m)
}
func (m *RWRun) XXX_DiscardUnknown() {
	xxx_messageInfo_RWRun.DiscardUnknown(m)
}

var xxx_messageInfo_RWRun proto.InternalMessageInfo

func (m *RWRun) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RWRun) GetOptions() *RWOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *RWRun) GetStats() []*RWRunStat {
	if m != nil {
		return m.Stats
	}
	return nil
}

type DPStats struct {
	DpRuns               []*DPRun `protobuf:"bytes,1,rep,name=dp_runs,json=dpRuns,proto3" json:"dp_runs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DPStats) Reset()         { *m = DPStats{} }
func (m *DPStats) String() string { return proto.CompactTextString(m) }
func (*DPStats) ProtoMessage()    {}
func (*DPStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{8}
}

func (m *DPStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DPStats.Unmarshal(m, b)
}
func (m *DPStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DPStats.Marshal(b, m, deterministic)
}
func (m *DPStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DPStats.Merge(m, src)
}
func (m *DPStats) XXX_Size() int {
	return xxx_messageInfo_DPStats.Size(m)
}
func (m *DPStats) XXX_DiscardUnknown() {
	xxx_messageInfo_DPStats.DiscardUnknown(m)
}

var xxx_messageInfo_DPStats proto.InternalMessageInfo

func (m *DPStats) GetDpRuns() []*DPRun {
	if m != nil {
		return m.DpRuns
	}
	return nil
}

type BufferStats struct {
	BufferRuns           []*BufferRun `protobuf:"bytes,1,rep,name=buffer_runs,json=bufferRuns,proto3" json:"buffer_runs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BufferStats) Reset()         { *m = BufferStats{} }
func (m *BufferStats) String() string { return proto.CompactTextString(m) }
func (*BufferStats) ProtoMessage()    {}
func (*BufferStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{9}
}

func (m *BufferStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BufferStats.Unmarshal(m, b)
}
func (m *BufferStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BufferStats.Marshal(b, m, deterministic)
}
func (m *BufferStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BufferStats.Merge(m, src)
}
func (m *BufferStats) XXX_Size() int {
	return xxx_messageInfo_BufferStats.Size(m)
}
func (m *BufferStats) XXX_DiscardUnknown() {
	xxx_messageInfo_BufferStats.DiscardUnknown(m)
}

var xxx_messageInfo_BufferStats proto.InternalMessageInfo

func (m *BufferStats) GetBufferRuns() []*BufferRun {
	if m != nil {
		return m.BufferRuns
	}
	return nil
}

type BufferRun struct {
	Timestamp            int64            `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Options              *BufferOptions   `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Stats                []*BufferRunStat `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BufferRun) Reset()         { *m = BufferRun{} }
func (m *BufferRun) String() string { return proto.CompactTextString(m) }
func (*BufferRun) ProtoMessage()    {}
func (*BufferRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{10}
}

func (m *BufferRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BufferRun.Unmarshal(m, b)
}
func (m *BufferRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BufferRun.Marshal(b, m, deterministic)
}
func (m *BufferRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BufferRun.Merge(m, src)
}
func (m *BufferRun) XXX_Size() int {
	return xxx_messageInfo_BufferRun.Size(m)
}
func (m *BufferRun) XXX_DiscardUnknown() {
	xxx_messageInfo_BufferRun.DiscardUnknown(m)
}

var xxx_messageInfo_BufferRun proto.InternalMessageInfo

func (m *BufferRun) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BufferRun) GetOptions() *BufferOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *BufferRun) GetStats() []*BufferRunStat {
	if m != nil {
		return m.Stats
	}
	return nil
}

type BufferRunStat struct {
	BufferStatNum        int64    `protobuf:"varint,1,opt,name=buffer_stat_num,json=bufferStatNum,proto3" json:"buffer_stat_num,omitempty"`
	ActionTimeMin        int64    `protobuf:"varint,2,opt,name=action_time_min,json=actionTimeMin,proto3" json:"action_time_min,omitempty"`
	ActionTimeMax        int64    `protobuf:"varint,3,opt,name=action_time_max,json=actionTimeMax,proto3" json:"action_time_max,omitempty"`
	ActionTimeTotal      int64    `protobuf:"varint,4,opt,name=action_time_total,json=actionTimeTotal,proto3" json:"action_time_total,omitempty"`
	WaitTimeMin          int64    `protobuf:"varint,5,opt,name=wait_time_min,json=waitTimeMin,proto3" json:"wait_time_min,omitempty"`
	WaitTimeMax          int64    `protobuf:"varint,6,opt,name=wait_time_max,json=waitTimeMax,proto3" json:"wait_time_max,omitempty"`
	WaitTimeTotal        int64    `protobuf:"varint,7,opt,name=wait_time_total,json=waitTimeTotal,proto3" json:"wait_time_total,omitempty"`
	Actions              int32    `protobuf:"varint,8,opt,name=actions,proto3" json:"actions,omitempty"`
	ActorType            string   `protobuf:"bytes,9,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BufferRunStat) Reset()         { *m = BufferRunStat{} }
func (m *BufferRunStat) String() string { return proto.CompactTextString(m) }
func (*BufferRunStat) ProtoMessage()    {}
func (*BufferRunStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{11}
}

func (m *BufferRunStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BufferRunStat.Unmarshal(m, b)
}
func (m *BufferRunStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BufferRunStat.Marshal(b, m, deterministic)
}
func (m *BufferRunStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BufferRunStat.Merge(m, src)
}
func (m *BufferRunStat) XXX_Size() int {
	return xxx_messageInfo_BufferRunStat.Size(m)
}
func (m *BufferRunStat) XXX_DiscardUnknown() {
	xxx_messageInfo_BufferRunStat.DiscardUnknown(m)
}

var xxx_messageInfo_BufferRunStat proto.InternalMessageInfo

func (m *BufferRunStat) GetBufferStatNum() int64 {
	if m != nil {
		return m.BufferStatNum
	}
	return 0
}

func (m *BufferRunStat) GetActionTimeMin() int64 {
	if m != nil {
		return m.ActionTimeMin
	}
	return 0
}

func (m *BufferRunStat) GetActionTimeMax() int64 {
	if m != nil {
		return m.ActionTimeMax
	}
	return 0
}

func (m *BufferRunStat) GetActionTimeTotal() int64 {
	if m != nil {
		return m.ActionTimeTotal
	}
	return 0
}

func (m *BufferRunStat) GetWaitTimeMin() int64 {
	if m != nil {
		return m.WaitTimeMin
	}
	return 0
}

func (m *BufferRunStat) GetWaitTimeMax() int64 {
	if m != nil {
		return m.WaitTimeMax
	}
	return 0
}

func (m *BufferRunStat) GetWaitTimeTotal() int64 {
	if m != nil {
		return m.WaitTimeTotal
	}
	return 0
}

func (m *BufferRunStat) GetActions() int32 {
	if m != nil {
		return m.Actions
	}
	return 0
}

func (m *BufferRunStat) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

type RWRunStat struct {
	ReadWriteNumber      int32    `protobuf:"varint,1,opt,name=read_write_number,json=readWriteNumber,proto3" json:"read_write_number,omitempty"`
	ActionTimeMin        int64    `protobuf:"varint,2,opt,name=action_time_min,json=actionTimeMin,proto3" json:"action_time_min,omitempty"`
	ActionTimeMax        int64    `protobuf:"varint,3,opt,name=action_time_max,json=actionTimeMax,proto3" json:"action_time_max,omitempty"`
	ActionTimeTotal      int64    `protobuf:"varint,4,opt,name=action_time_total,json=actionTimeTotal,proto3" json:"action_time_total,omitempty"`
	WaitTimeMin          int64    `protobuf:"varint,5,opt,name=wait_time_min,json=waitTimeMin,proto3" json:"wait_time_min,omitempty"`
	WaitTimeMax          int64    `protobuf:"varint,6,opt,name=wait_time_max,json=waitTimeMax,proto3" json:"wait_time_max,omitempty"`
	WaitTimeTotal        int64    `protobuf:"varint,7,opt,name=wait_time_total,json=waitTimeTotal,proto3" json:"wait_time_total,omitempty"`
	Actions              int32    `protobuf:"varint,8,opt,name=actions,proto3" json:"actions,omitempty"`
	ActorType            string   `protobuf:"bytes,9,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RWRunStat) Reset()         { *m = RWRunStat{} }
func (m *RWRunStat) String() string { return proto.CompactTextString(m) }
func (*RWRunStat) ProtoMessage()    {}
func (*RWRunStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{12}
}

func (m *RWRunStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RWRunStat.Unmarshal(m, b)
}
func (m *RWRunStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RWRunStat.Marshal(b, m, deterministic)
}
func (m *RWRunStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RWRunStat.Merge(m, src)
}
func (m *RWRunStat) XXX_Size() int {
	return xxx_messageInfo_RWRunStat.Size(m)
}
func (m *RWRunStat) XXX_DiscardUnknown() {
	xxx_messageInfo_RWRunStat.DiscardUnknown(m)
}

var xxx_messageInfo_RWRunStat proto.InternalMessageInfo

func (m *RWRunStat) GetReadWriteNumber() int32 {
	if m != nil {
		return m.ReadWriteNumber
	}
	return 0
}

func (m *RWRunStat) GetActionTimeMin() int64 {
	if m != nil {
		return m.ActionTimeMin
	}
	return 0
}

func (m *RWRunStat) GetActionTimeMax() int64 {
	if m != nil {
		return m.ActionTimeMax
	}
	return 0
}

func (m *RWRunStat) GetActionTimeTotal() int64 {
	if m != nil {
		return m.ActionTimeTotal
	}
	return 0
}

func (m *RWRunStat) GetWaitTimeMin() int64 {
	if m != nil {
		return m.WaitTimeMin
	}
	return 0
}

func (m *RWRunStat) GetWaitTimeMax() int64 {
	if m != nil {
		return m.WaitTimeMax
	}
	return 0
}

func (m *RWRunStat) GetWaitTimeTotal() int64 {
	if m != nil {
		return m.WaitTimeTotal
	}
	return 0
}

func (m *RWRunStat) GetActions() int32 {
	if m != nil {
		return m.Actions
	}
	return 0
}

func (m *RWRunStat) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

type BufferOptions struct {
	BufferSize           int32     `protobuf:"varint,1,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	NumProducers         int32     `protobuf:"varint,2,opt,name=num_producers,json=numProducers,proto3" json:"num_producers,omitempty"`
	NumConsumers         int32     `protobuf:"varint,3,opt,name=num_consumers,json=numConsumers,proto3" json:"num_consumers,omitempty"`
	ProduceTime          int64     `protobuf:"varint,4,opt,name=produce_time,json=produceTime,proto3" json:"produce_time,omitempty"`
	ConsumeTime          int64     `protobuf:"varint,5,opt,name=consume_time,json=consumeTime,proto3" json:"consume_time,omitempty"`
	Variation            int64     `protobuf:"varint,6,opt,name=variation,proto3" json:"variation,omitempty"`
	Duration             int64     `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	SleepTime            int64     `protobuf:"varint,8,opt,name=sleep_time,json=sleepTime,proto3" json:"sleep_time,omitempty"`
	SaveCode             *SaveCode `protobuf:"bytes,9,opt,name=save_code,json=saveCode,proto3" json:"save_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BufferOptions) Reset()         { *m = BufferOptions{} }
func (m *BufferOptions) String() string { return proto.CompactTextString(m) }
func (*BufferOptions) ProtoMessage()    {}
func (*BufferOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{13}
}

func (m *BufferOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BufferOptions.Unmarshal(m, b)
}
func (m *BufferOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BufferOptions.Marshal(b, m, deterministic)
}
func (m *BufferOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BufferOptions.Merge(m, src)
}
func (m *BufferOptions) XXX_Size() int {
	return xxx_messageInfo_BufferOptions.Size(m)
}
func (m *BufferOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BufferOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BufferOptions proto.InternalMessageInfo

func (m *BufferOptions) GetBufferSize() int32 {
	if m != nil {
		return m.BufferSize
	}
	return 0
}

func (m *BufferOptions) GetNumProducers() int32 {
	if m != nil {
		return m.NumProducers
	}
	return 0
}

func (m *BufferOptions) GetNumConsumers() int32 {
	if m != nil {
		return m.NumConsumers
	}
	return 0
}

func (m *BufferOptions) GetProduceTime() int64 {
	if m != nil {
		return m.ProduceTime
	}
	return 0
}

func (m *BufferOptions) GetConsumeTime() int64 {
	if m != nil {
		return m.ConsumeTime
	}
	return 0
}

func (m *BufferOptions) GetVariation() int64 {
	if m != nil {
		return m.Variation
	}
	return 0
}

func (m *BufferOptions) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *BufferOptions) GetSleepTime() int64 {
	if m != nil {
		return m.SleepTime
	}
	return 0
}

func (m *BufferOptions) GetSaveCode() *SaveCode {
	if m != nil {
		return m.SaveCode
	}
	return nil
}

type BufferState struct {
	Id                   int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State                BufferState_State `protobuf:"varint,2,opt,name=state,proto3,enum=BufferState_State" json:"state,omitempty"`
	Time                 int64             `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Actor                string            `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BufferState) Reset()         { *m = BufferState{} }
func (m *BufferState) String() string { return proto.CompactTextString(m) }
func (*BufferState) ProtoMessage()    {}
func (*BufferState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{14}
}

func (m *BufferState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BufferState.Unmarshal(m, b)
}
func (m *BufferState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BufferState.Marshal(b, m, deterministic)
}
func (m *BufferState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BufferState.Merge(m, src)
}
func (m *BufferState) XXX_Size() int {
	return xxx_messageInfo_BufferState.Size(m)
}
func (m *BufferState) XXX_DiscardUnknown() {
	xxx_messageInfo_BufferState.DiscardUnknown(m)
}

var xxx_messageInfo_BufferState proto.InternalMessageInfo

func (m *BufferState) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BufferState) GetState() BufferState_State {
	if m != nil {
		return m.State
	}
	return BufferState_UNDEFINED
}

func (m *BufferState) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *BufferState) GetActor() string {
	if m != nil {
		return m.Actor
	}
	return ""
}

type ModusOptions struct {
	Duration             int64    `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	TotalHeathens        int32    `protobuf:"varint,2,opt,name=total_heathens,json=totalHeathens,proto3" json:"total_heathens,omitempty"`
	TotalPrudes          int32    `protobuf:"varint,3,opt,name=total_prudes,json=totalPrudes,proto3" json:"total_prudes,omitempty"`
	TimeToCrossMin       int64    `protobuf:"varint,4,opt,name=time_to_cross_min,json=timeToCrossMin,proto3" json:"time_to_cross_min,omitempty"`
	TimeToCrossMax       int64    `protobuf:"varint,5,opt,name=time_to_cross_max,json=timeToCrossMax,proto3" json:"time_to_cross_max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModusOptions) Reset()         { *m = ModusOptions{} }
func (m *ModusOptions) String() string { return proto.CompactTextString(m) }
func (*ModusOptions) ProtoMessage()    {}
func (*ModusOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{15}
}

func (m *ModusOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModusOptions.Unmarshal(m, b)
}
func (m *ModusOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModusOptions.Marshal(b, m, deterministic)
}
func (m *ModusOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModusOptions.Merge(m, src)
}
func (m *ModusOptions) XXX_Size() int {
	return xxx_messageInfo_ModusOptions.Size(m)
}
func (m *ModusOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ModusOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ModusOptions proto.InternalMessageInfo

func (m *ModusOptions) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *ModusOptions) GetTotalHeathens() int32 {
	if m != nil {
		return m.TotalHeathens
	}
	return 0
}

func (m *ModusOptions) GetTotalPrudes() int32 {
	if m != nil {
		return m.TotalPrudes
	}
	return 0
}

func (m *ModusOptions) GetTimeToCrossMin() int64 {
	if m != nil {
		return m.TimeToCrossMin
	}
	return 0
}

func (m *ModusOptions) GetTimeToCrossMax() int64 {
	if m != nil {
		return m.TimeToCrossMax
	}
	return 0
}

type ModusState struct {
	Id                   int32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State                ModusState_State `protobuf:"varint,2,opt,name=state,proto3,enum=ModusState_State" json:"state,omitempty"`
	Time                 int64            `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ModusState) Reset()         { *m = ModusState{} }
func (m *ModusState) String() string { return proto.CompactTextString(m) }
func (*ModusState) ProtoMessage()    {}
func (*ModusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{16}
}

func (m *ModusState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModusState.Unmarshal(m, b)
}
func (m *ModusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModusState.Marshal(b, m, deterministic)
}
func (m *ModusState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModusState.Merge(m, src)
}
func (m *ModusState) XXX_Size() int {
	return xxx_messageInfo_ModusState.Size(m)
}
func (m *ModusState) XXX_DiscardUnknown() {
	xxx_messageInfo_ModusState.DiscardUnknown(m)
}

var xxx_messageInfo_ModusState proto.InternalMessageInfo

func (m *ModusState) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModusState) GetState() ModusState_State {
	if m != nil {
		return m.State
	}
	return ModusState_UNDEFINED
}

func (m *ModusState) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type UnisexOptions struct {
	Duration             int64                  `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Solution             UnisexOptions_Solution `protobuf:"varint,2,opt,name=solution,proto3,enum=UnisexOptions_Solution" json:"solution,omitempty"`
	NumMales             int32                  `protobuf:"varint,3,opt,name=num_males,json=numMales,proto3" json:"num_males,omitempty"`
	NumFemales           int32                  `protobuf:"varint,4,opt,name=num_females,json=numFemales,proto3" json:"num_females,omitempty"`
	MaxAllowed           int32                  `protobuf:"varint,5,opt,name=max_allowed,json=maxAllowed,proto3" json:"max_allowed,omitempty"`
	MaleTime             int64                  `protobuf:"varint,6,opt,name=male_time,json=maleTime,proto3" json:"male_time,omitempty"`
	FemaleTime           int64                  `protobuf:"varint,7,opt,name=female_time,json=femaleTime,proto3" json:"female_time,omitempty"`
	RestartTime          int64                  `protobuf:"varint,8,opt,name=restart_time,json=restartTime,proto3" json:"restart_time,omitempty"`
	Variation            int64                  `protobuf:"varint,9,opt,name=variation,proto3" json:"variation,omitempty"`
	SaveCode             *SaveCode              `protobuf:"bytes,10,opt,name=save_code,json=saveCode,proto3" json:"save_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UnisexOptions) Reset()         { *m = UnisexOptions{} }
func (m *UnisexOptions) String() string { return proto.CompactTextString(m) }
func (*UnisexOptions) ProtoMessage()    {}
func (*UnisexOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{17}
}

func (m *UnisexOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnisexOptions.Unmarshal(m, b)
}
func (m *UnisexOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnisexOptions.Marshal(b, m, deterministic)
}
func (m *UnisexOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnisexOptions.Merge(m, src)
}
func (m *UnisexOptions) XXX_Size() int {
	return xxx_messageInfo_UnisexOptions.Size(m)
}
func (m *UnisexOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_UnisexOptions.DiscardUnknown(m)
}

var xxx_messageInfo_UnisexOptions proto.InternalMessageInfo

func (m *UnisexOptions) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *UnisexOptions) GetSolution() UnisexOptions_Solution {
	if m != nil {
		return m.Solution
	}
	return UnisexOptions_UNDEFINED
}

func (m *UnisexOptions) GetNumMales() int32 {
	if m != nil {
		return m.NumMales
	}
	return 0
}

func (m *UnisexOptions) GetNumFemales() int32 {
	if m != nil {
		return m.NumFemales
	}
	return 0
}

func (m *UnisexOptions) GetMaxAllowed() int32 {
	if m != nil {
		return m.MaxAllowed
	}
	return 0
}

func (m *UnisexOptions) GetMaleTime() int64 {
	if m != nil {
		return m.MaleTime
	}
	return 0
}

func (m *UnisexOptions) GetFemaleTime() int64 {
	if m != nil {
		return m.FemaleTime
	}
	return 0
}

func (m *UnisexOptions) GetRestartTime() int64 {
	if m != nil {
		return m.RestartTime
	}
	return 0
}

func (m *UnisexOptions) GetVariation() int64 {
	if m != nil {
		return m.Variation
	}
	return 0
}

func (m *UnisexOptions) GetSaveCode() *SaveCode {
	if m != nil {
		return m.SaveCode
	}
	return nil
}

type UnisexState struct {
	Id                   int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State                UnisexState_State `protobuf:"varint,2,opt,name=state,proto3,enum=UnisexState_State" json:"state,omitempty"`
	Time                 int64             `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UnisexState) Reset()         { *m = UnisexState{} }
func (m *UnisexState) String() string { return proto.CompactTextString(m) }
func (*UnisexState) ProtoMessage()    {}
func (*UnisexState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{18}
}

func (m *UnisexState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnisexState.Unmarshal(m, b)
}
func (m *UnisexState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnisexState.Marshal(b, m, deterministic)
}
func (m *UnisexState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnisexState.Merge(m, src)
}
func (m *UnisexState) XXX_Size() int {
	return xxx_messageInfo_UnisexState.Size(m)
}
func (m *UnisexState) XXX_DiscardUnknown() {
	xxx_messageInfo_UnisexState.DiscardUnknown(m)
}

var xxx_messageInfo_UnisexState proto.InternalMessageInfo

func (m *UnisexState) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UnisexState) GetState() UnisexState_State {
	if m != nil {
		return m.State
	}
	return UnisexState_UNDEFINED
}

func (m *UnisexState) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type UnisexStats struct {
	UnisexRuns           []*UnisexRun `protobuf:"bytes,1,rep,name=unisex_runs,json=unisexRuns,proto3" json:"unisex_runs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UnisexStats) Reset()         { *m = UnisexStats{} }
func (m *UnisexStats) String() string { return proto.CompactTextString(m) }
func (*UnisexStats) ProtoMessage()    {}
func (*UnisexStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{19}
}

func (m *UnisexStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnisexStats.Unmarshal(m, b)
}
func (m *UnisexStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnisexStats.Marshal(b, m, deterministic)
}
func (m *UnisexStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnisexStats.Merge(m, src)
}
func (m *UnisexStats) XXX_Size() int {
	return xxx_messageInfo_UnisexStats.Size(m)
}
func (m *UnisexStats) XXX_DiscardUnknown() {
	xxx_messageInfo_UnisexStats.DiscardUnknown(m)
}

var xxx_messageInfo_UnisexStats proto.InternalMessageInfo

func (m *UnisexStats) GetUnisexRuns() []*UnisexRun {
	if m != nil {
		return m.UnisexRuns
	}
	return nil
}

type UnisexRun struct {
	Timestamp            int64            `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Options              *UnisexOptions   `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Stats                []*UnisexRunStat `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UnisexRun) Reset()         { *m = UnisexRun{} }
func (m *UnisexRun) String() string { return proto.CompactTextString(m) }
func (*UnisexRun) ProtoMessage()    {}
func (*UnisexRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{20}
}

func (m *UnisexRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnisexRun.Unmarshal(m, b)
}
func (m *UnisexRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnisexRun.Marshal(b, m, deterministic)
}
func (m *UnisexRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnisexRun.Merge(m, src)
}
func (m *UnisexRun) XXX_Size() int {
	return xxx_messageInfo_UnisexRun.Size(m)
}
func (m *UnisexRun) XXX_DiscardUnknown() {
	xxx_messageInfo_UnisexRun.DiscardUnknown(m)
}

var xxx_messageInfo_UnisexRun proto.InternalMessageInfo

func (m *UnisexRun) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UnisexRun) GetOptions() *UnisexOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *UnisexRun) GetStats() []*UnisexRunStat {
	if m != nil {
		return m.Stats
	}
	return nil
}

type UnisexRunStat struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeUsingMin         int64    `protobuf:"varint,2,opt,name=time_using_min,json=timeUsingMin,proto3" json:"time_using_min,omitempty"`
	TimeUsingMax         int64    `protobuf:"varint,3,opt,name=time_using_max,json=timeUsingMax,proto3" json:"time_using_max,omitempty"`
	TimeUsingTotal       int64    `protobuf:"varint,5,opt,name=time_using_total,json=timeUsingTotal,proto3" json:"time_using_total,omitempty"`
	TimesUsed            int64    `protobuf:"varint,6,opt,name=times_used,json=timesUsed,proto3" json:"times_used,omitempty"`
	WaitTimeMin          int64    `protobuf:"varint,8,opt,name=wait_time_min,json=waitTimeMin,proto3" json:"wait_time_min,omitempty"`
	WaitTimeMax          int64    `protobuf:"varint,9,opt,name=wait_time_max,json=waitTimeMax,proto3" json:"wait_time_max,omitempty"`
	WaitTimeTotal        int64    `protobuf:"varint,11,opt,name=wait_time_total,json=waitTimeTotal,proto3" json:"wait_time_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnisexRunStat) Reset()         { *m = UnisexRunStat{} }
func (m *UnisexRunStat) String() string { return proto.CompactTextString(m) }
func (*UnisexRunStat) ProtoMessage()    {}
func (*UnisexRunStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{21}
}

func (m *UnisexRunStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnisexRunStat.Unmarshal(m, b)
}
func (m *UnisexRunStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnisexRunStat.Marshal(b, m, deterministic)
}
func (m *UnisexRunStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnisexRunStat.Merge(m, src)
}
func (m *UnisexRunStat) XXX_Size() int {
	return xxx_messageInfo_UnisexRunStat.Size(m)
}
func (m *UnisexRunStat) XXX_DiscardUnknown() {
	xxx_messageInfo_UnisexRunStat.DiscardUnknown(m)
}

var xxx_messageInfo_UnisexRunStat proto.InternalMessageInfo

func (m *UnisexRunStat) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UnisexRunStat) GetTimeUsingMin() int64 {
	if m != nil {
		return m.TimeUsingMin
	}
	return 0
}

func (m *UnisexRunStat) GetTimeUsingMax() int64 {
	if m != nil {
		return m.TimeUsingMax
	}
	return 0
}

func (m *UnisexRunStat) GetTimeUsingTotal() int64 {
	if m != nil {
		return m.TimeUsingTotal
	}
	return 0
}

func (m *UnisexRunStat) GetTimesUsed() int64 {
	if m != nil {
		return m.TimesUsed
	}
	return 0
}

func (m *UnisexRunStat) GetWaitTimeMin() int64 {
	if m != nil {
		return m.WaitTimeMin
	}
	return 0
}

func (m *UnisexRunStat) GetWaitTimeMax() int64 {
	if m != nil {
		return m.WaitTimeMax
	}
	return 0
}

func (m *UnisexRunStat) GetWaitTimeTotal() int64 {
	if m != nil {
		return m.WaitTimeTotal
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{22}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type SaveCode struct {
	SaveCode             string   `protobuf:"bytes,1,opt,name=save_code,json=saveCode,proto3" json:"save_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveCode) Reset()         { *m = SaveCode{} }
func (m *SaveCode) String() string { return proto.CompactTextString(m) }
func (*SaveCode) ProtoMessage()    {}
func (*SaveCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{23}
}

func (m *SaveCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveCode.Unmarshal(m, b)
}
func (m *SaveCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveCode.Marshal(b, m, deterministic)
}
func (m *SaveCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveCode.Merge(m, src)
}
func (m *SaveCode) XXX_Size() int {
	return xxx_messageInfo_SaveCode.Size(m)
}
func (m *SaveCode) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveCode.DiscardUnknown(m)
}

var xxx_messageInfo_SaveCode proto.InternalMessageInfo

func (m *SaveCode) GetSaveCode() string {
	if m != nil {
		return m.SaveCode
	}
	return ""
}

type SaveCodeValidationResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveCodeValidationResponse) Reset()         { *m = SaveCodeValidationResponse{} }
func (m *SaveCodeValidationResponse) String() string { return proto.CompactTextString(m) }
func (*SaveCodeValidationResponse) ProtoMessage()    {}
func (*SaveCodeValidationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0796301471099, []int{24}
}

func (m *SaveCodeValidationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveCodeValidationResponse.Unmarshal(m, b)
}
func (m *SaveCodeValidationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveCodeValidationResponse.Marshal(b, m, deterministic)
}
func (m *SaveCodeValidationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveCodeValidationResponse.Merge(m, src)
}
func (m *SaveCodeValidationResponse) XXX_Size() int {
	return xxx_messageInfo_SaveCodeValidationResponse.Size(m)
}
func (m *SaveCodeValidationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveCodeValidationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveCodeValidationResponse proto.InternalMessageInfo

func (m *SaveCodeValidationResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterEnum("DPState_State", DPState_State_name, DPState_State_value)
	proto.RegisterEnum("RWOptions_Solution", RWOptions_Solution_name, RWOptions_Solution_value)
	proto.RegisterEnum("RWState_State", RWState_State_name, RWState_State_value)
	proto.RegisterEnum("BufferState_State", BufferState_State_name, BufferState_State_value)
	proto.RegisterEnum("ModusState_State", ModusState_State_name, ModusState_State_value)
	proto.RegisterEnum("UnisexOptions_Solution", UnisexOptions_Solution_name, UnisexOptions_Solution_value)
	proto.RegisterEnum("UnisexState_State", UnisexState_State_name, UnisexState_State_value)
	proto.RegisterType((*DPState)(nil), "DPState")
	proto.RegisterType((*DPOptions)(nil), "DPOptions")
	proto.RegisterType((*DPRun)(nil), "DPRun")
	proto.RegisterType((*DPStat)(nil), "DPStat")
	proto.RegisterType((*RWOptions)(nil), "RWOptions")
	proto.RegisterType((*RWState)(nil), "RWState")
	proto.RegisterType((*RWStats)(nil), "RWStats")
	proto.RegisterType((*RWRun)(nil), "RWRun")
	proto.RegisterType((*DPStats)(nil), "DPStats")
	proto.RegisterType((*BufferStats)(nil), "BufferStats")
	proto.RegisterType((*BufferRun)(nil), "BufferRun")
	proto.RegisterType((*BufferRunStat)(nil), "BufferRunStat")
	proto.RegisterType((*RWRunStat)(nil), "RWRunStat")
	proto.RegisterType((*BufferOptions)(nil), "BufferOptions")
	proto.RegisterType((*BufferState)(nil), "BufferState")
	proto.RegisterType((*ModusOptions)(nil), "ModusOptions")
	proto.RegisterType((*ModusState)(nil), "ModusState")
	proto.RegisterType((*UnisexOptions)(nil), "UnisexOptions")
	proto.RegisterType((*UnisexState)(nil), "UnisexState")
	proto.RegisterType((*UnisexStats)(nil), "UnisexStats")
	proto.RegisterType((*UnisexRun)(nil), "UnisexRun")
	proto.RegisterType((*UnisexRunStat)(nil), "UnisexRunStat")
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*SaveCode)(nil), "SaveCode")
	proto.RegisterType((*SaveCodeValidationResponse)(nil), "SaveCodeValidationResponse")
}

func init() { proto.RegisterFile("css.proto", fileDescriptor_dbc0796301471099) }

var fileDescriptor_dbc0796301471099 = []byte{
	// 2245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcd, 0x6e, 0xdb, 0xd8,
	0x15, 0xae, 0xfe, 0xc5, 0xa3, 0x1f, 0xd3, 0x37, 0x7f, 0xae, 0xa7, 0x69, 0x1c, 0x4d, 0x26, 0xe3,
	0x49, 0x51, 0x79, 0xe0, 0xec, 0x66, 0xa7, 0x48, 0x94, 0x2d, 0xc4, 0x96, 0x94, 0x2b, 0x2a, 0x9e,
	0x74, 0x43, 0xd0, 0x22, 0x13, 0x13, 0x91, 0x48, 0x41, 0x24, 0x63, 0xb9, 0xdb, 0xce, 0xaa, 0x40,
	0x9f, 0xa0, 0x40, 0x81, 0x02, 0x45, 0xfb, 0x1c, 0xdd, 0x16, 0xe8, 0x1b, 0x14, 0xe8, 0x2b, 0x74,
	0xd7, 0x55, 0x8b, 0xe2, 0xdc, 0x1f, 0xf2, 0x52, 0xb6, 0x93, 0xcc, 0xbe, 0x1b, 0x41, 0xf7, 0x3b,
	0x1f, 0xef, 0xe1, 0x3d, 0xf7, 0xdc, 0x73, 0xbf, 0x43, 0xd0, 0x66, 0x61, 0xd8, 0x5e, 0xae, 0x82,
	0x28, 0x68, 0xfd, 0x2e, 0x0f, 0x95, 0xde, 0x78, 0x12, 0xd9, 0x91, 0x4b, 0x9a, 0x90, 0xf7, 0x9c,
	0x9d, 0xdc, 0x5e, 0x6e, 0xbf, 0x44, 0xf3, 0x9e, 0x43, 0x9e, 0x40, 0x29, 0x44, 0xc3, 0x4e, 0x7e,
	0x2f, 0xb7, 0xdf, 0x3c, 0x6c, 0xb6, 0x05, 0xb1, 0xcd, 0x7e, 0x29, 0x37, 0x92, 0x07, 0x50, 0x79,
	0x1b, 0xac, 0xde, 0x5b, 0x9e, 0xb3, 0x53, 0x60, 0x8f, 0x96, 0x71, 0x38, 0x70, 0x08, 0x81, 0x62,
	0xe4, 0x2d, 0xdc, 0x9d, 0xe2, 0x5e, 0x6e, 0xbf, 0x40, 0xd9, 0xff, 0xd6, 0x1f, 0x72, 0x50, 0xe2,
	0xce, 0x1a, 0xa0, 0x4d, 0x87, 0x3d, 0xa3, 0x3f, 0x18, 0x1a, 0x3d, 0xfd, 0x27, 0xe4, 0x0e, 0x6c,
	0x51, 0xe3, 0xd5, 0xd4, 0x98, 0x98, 0x83, 0xe1, 0x91, 0xd5, 0x1f, 0xd1, 0x97, 0x7a, 0x8e, 0xe8,
	0x50, 0x3f, 0x1e, 0x9d, 0xf4, 0x12, 0x24, 0x4f, 0x08, 0x34, 0xa9, 0x71, 0x62, 0x74, 0x26, 0x09,
	0x56, 0x20, 0x00, 0xe5, 0xe3, 0xe9, 0xf0, 0x88, 0xbe, 0xd1, 0x8b, 0xf8, 0xdf, 0xe8, 0xe0, 0x14,
	0x7a, 0x89, 0xd4, 0xa1, 0x6a, 0x1e, 0x0f, 0x86, 0x2f, 0x71, 0x54, 0x26, 0xf7, 0x60, 0xfb, 0x88,
	0x76, 0xba, 0x46, 0x7f, 0x7a, 0x72, 0xf2, 0xc6, 0x32, 0xbe, 0x1f, 0x98, 0x46, 0x4f, 0xaf, 0x90,
	0x26, 0x40, 0xcf, 0xe8, 0xf4, 0x4e, 0x46, 0xdd, 0x97, 0x46, 0x4f, 0xaf, 0xb6, 0xfe, 0x99, 0x03,
	0xad, 0x37, 0x1e, 0x2d, 0x23, 0x2f, 0xf0, 0x43, 0x72, 0x1f, 0xca, 0xb3, 0x8b, 0xc0, 0x9b, 0xb9,
	0x22, 0x2a, 0x62, 0x44, 0x76, 0xa1, 0xea, 0xc4, 0x2b, 0x1b, 0x49, 0x2c, 0x38, 0x05, 0x9a, 0x8c,
	0x71, 0xd9, 0xa1, 0xf7, 0x6b, 0x57, 0x04, 0x83, 0xfd, 0x27, 0x5f, 0x42, 0x03, 0x97, 0x6f, 0x45,
	0x17, 0x9e, 0xff, 0xde, 0xf3, 0xdf, 0x89, 0x98, 0xd4, 0x11, 0x34, 0x05, 0x46, 0x1e, 0x41, 0x8d,
	0x91, 0x5c, 0x3b, 0x42, 0x4a, 0x89, 0x51, 0x00, 0x21, 0x83, 0x21, 0xe4, 0x67, 0xa0, 0x7d, 0xb0,
	0x57, 0x1e, 0x77, 0x5b, 0x66, 0xe6, 0x14, 0x20, 0x4f, 0x41, 0x0b, 0xed, 0x0f, 0xae, 0x35, 0x0b,
	0x1c, 0x77, 0xa7, 0xb2, 0x97, 0xdb, 0xaf, 0x1d, 0x6a, 0xed, 0x89, 0xfd, 0xc1, 0xed, 0x06, 0x8e,
	0x4b, 0xab, 0xa1, 0xf8, 0xd7, 0xfa, 0x6d, 0x0e, 0x4a, 0xbd, 0x31, 0x8d, 0x7d, 0x9c, 0x0f, 0x67,
	0x0f, 0x23, 0x7b, 0xb1, 0x64, 0x0b, 0x2c, 0xd0, 0x14, 0x20, 0x4f, 0xa0, 0x12, 0xf0, 0x30, 0xb0,
	0x25, 0xd6, 0x0e, 0xa1, 0x9d, 0x04, 0x86, 0x4a, 0x13, 0xf9, 0x39, 0x80, 0xe3, 0xda, 0xce, 0x3c,
	0x98, 0xbd, 0x77, 0x79, 0x02, 0x54, 0xa9, 0x82, 0x90, 0x87, 0x3c, 0x87, 0xc2, 0x9d, 0xe2, 0x5e,
	0x61, 0xbf, 0x76, 0x58, 0x11, 0x39, 0xc4, 0x93, 0x27, 0x6c, 0xfd, 0x37, 0x0f, 0x65, 0x8e, 0x90,
	0x5f, 0x02, 0x59, 0x5e, 0x78, 0xf3, 0x20, 0x0c, 0x96, 0x17, 0xee, 0xca, 0xf2, 0xe3, 0xc5, 0xb9,
	0xbb, 0x12, 0x71, 0xdf, 0x56, 0x2c, 0x43, 0x66, 0x20, 0x0f, 0x01, 0x16, 0xf6, 0xda, 0xba, 0x88,
	0xfd, 0x77, 0xab, 0x2b, 0xb1, 0x09, 0xda, 0xc2, 0x5e, 0x1f, 0x33, 0x40, 0x9a, 0x45, 0x2c, 0x0b,
	0x89, 0x59, 0x84, 0xf2, 0x31, 0xd4, 0xd1, 0xbc, 0xb1, 0x1f, 0xb5, 0x85, 0xbd, 0x4e, 0xb6, 0x03,
	0x67, 0xf0, 0x7c, 0xe9, 0xa0, 0x24, 0x66, 0xf0, 0x7c, 0xc5, 0x81, 0xe7, 0x4b, 0x07, 0xe5, 0xc4,
	0xac, 0x38, 0xf0, 0xfc, 0xd4, 0x41, 0x45, 0x38, 0xf0, 0xfc, 0xc4, 0xc1, 0x63, 0xa8, 0x47, 0x41,
	0x64, 0xcf, 0xa5, 0x8b, 0x2a, 0xa7, 0x30, 0x4c, 0x38, 0x49, 0x28, 0xc2, 0x8d, 0xa6, 0x50, 0x84,
	0xa3, 0xaf, 0xa0, 0xc9, 0x29, 0x89, 0x2b, 0x60, 0xa4, 0x06, 0x43, 0x13, 0x67, 0x98, 0xc9, 0x57,
	0xb3, 0xb9, 0x1b, 0xee, 0xd4, 0x44, 0x26, 0xb3, 0x51, 0xeb, 0xef, 0x05, 0xd0, 0xe8, 0x99, 0xcc,
	0xf7, 0x47, 0x50, 0xf3, 0xe3, 0x85, 0xb5, 0x72, 0x6d, 0xc7, 0x5d, 0x85, 0x22, 0xf8, 0xe0, 0xc7,
	0x0b, 0xca, 0x11, 0x49, 0xb8, 0x5c, 0x79, 0x11, 0x12, 0xf2, 0x09, 0xe1, 0x8c, 0x23, 0xe4, 0x00,
	0xaa, 0x61, 0x30, 0x8f, 0x59, 0x8a, 0x16, 0x58, 0xd9, 0xb8, 0xd3, 0x4e, 0xe6, 0x6f, 0x4f, 0x84,
	0x89, 0x26, 0xa4, 0xcc, 0x51, 0x2a, 0x6e, 0x1c, 0xa5, 0x2f, 0xa1, 0x81, 0xaf, 0x62, 0x25, 0x04,
	0xbe, 0x0b, 0x75, 0x04, 0x7b, 0x92, 0xf4, 0x15, 0x34, 0xd9, 0xeb, 0xa4, 0x2c, 0xbe, 0x19, 0x0d,
	0x86, 0x26, 0xb4, 0xcc, 0xe1, 0xa9, 0x6c, 0x1e, 0x9e, 0x87, 0x00, 0xcc, 0x53, 0x38, 0x77, 0xdd,
	0xa5, 0xd8, 0x09, 0x0d, 0x91, 0x09, 0x02, 0xb8, 0x6c, 0xee, 0x83, 0xdb, 0xf9, 0x36, 0x00, 0x83,
	0x38, 0x21, 0x73, 0xf8, 0xe0, 0xf6, 0xc3, 0x67, 0x41, 0x55, 0xc6, 0x80, 0x6c, 0x41, 0x6d, 0x3a,
	0x9c, 0x8c, 0x8d, 0xee, 0xa0, 0x3f, 0x60, 0x35, 0xf0, 0x2e, 0xe8, 0xfd, 0x01, 0x9d, 0x98, 0xd6,
	0xc4, 0xec, 0xd0, 0xd7, 0x1d, 0x73, 0x30, 0x1a, 0xea, 0x39, 0xf2, 0x00, 0xee, 0x0c, 0x47, 0x1c,
	0x32, 0x2c, 0x73, 0x4a, 0x87, 0x13, 0x73, 0x70, 0x62, 0xe8, 0x79, 0x2c, 0x99, 0x67, 0x74, 0x60,
	0x1a, 0xd4, 0x1a, 0xd3, 0xc1, 0x88, 0x0e, 0xcc, 0x37, 0x7a, 0xa1, 0xf5, 0xaf, 0x22, 0x54, 0xe8,
	0xd9, 0xcd, 0xf5, 0x5c, 0x16, 0xe4, 0x7c, 0x5a, 0x90, 0xd3, 0x1a, 0x5f, 0x10, 0x35, 0x5e, 0x3c,
	0x9c, 0xad, 0xf1, 0x77, 0xa1, 0x64, 0xcf, 0xa2, 0x60, 0xc5, 0x76, 0x48, 0xa3, 0x7c, 0xd0, 0xfa,
	0xa1, 0x78, 0x4b, 0x31, 0xaf, 0x41, 0x85, 0x1a, 0x1d, 0xac, 0xdb, 0x7a, 0x0e, 0x07, 0xf8, 0x9a,
	0x38, 0xc8, 0x63, 0x15, 0x3e, 0xeb, 0x0c, 0x64, 0x8d, 0xb7, 0x4e, 0xa7, 0xa6, 0xf1, 0xbd, 0x5e,
	0xc0, 0xb2, 0xde, 0xe9, 0xbe, 0x9a, 0x0e, 0xa8, 0xd1, 0x13, 0x58, 0x31, 0x2d, 0xf5, 0x09, 0x56,
	0x22, 0xbb, 0x70, 0x5f, 0x7d, 0x9c, 0x8e, 0x46, 0xa7, 0x96, 0x71, 0x3a, 0x36, 0xdf, 0xe8, 0x65,
	0x8c, 0x13, 0x35, 0xba, 0xc6, 0xe0, 0xb5, 0xd1, 0x53, 0x0d, 0x15, 0xf4, 0x39, 0x19, 0x1c, 0x0d,
	0x3b, 0x27, 0x2a, 0x5c, 0x25, 0x3f, 0x85, 0x7b, 0xea, 0x5c, 0x69, 0x64, 0x35, 0x7c, 0xc2, 0x3c,
	0xa6, 0xa3, 0xe9, 0xd1, 0xb1, 0x02, 0x03, 0xc2, 0xc6, 0x10, 0xe3, 0x8d, 0x8b, 0xb3, 0x26, 0x67,
	0x03, 0xb3, 0x7b, 0xac, 0xd7, 0x10, 0x3e, 0x31, 0x3a, 0xaf, 0x8d, 0x0c, 0x5c, 0x27, 0xf7, 0x81,
	0x70, 0x36, 0xdb, 0x24, 0x89, 0x37, 0x10, 0xe7, 0xf4, 0x0c, 0xde, 0xdc, 0x5c, 0xdb, 0x70, 0xc4,
	0xe6, 0x33, 0xe8, 0x44, 0xdf, 0xba, 0xc1, 0xc6, 0x77, 0x7e, 0xa2, 0xeb, 0xca, 0xf2, 0x94, 0x47,
	0xb6, 0xb3, 0xb0, 0x64, 0x93, 0x4c, 0x94, 0x14, 0xfe, 0x9d, 0x4d, 0x83, 0x7c, 0xe2, 0x2e, 0xde,
	0x90, 0xc6, 0xb0, 0x67, 0x75, 0xba, 0x2c, 0x1f, 0xef, 0x61, 0xda, 0xe2, 0xbb, 0x48, 0xe0, 0x7e,
	0xeb, 0x99, 0xcc, 0x38, 0x2c, 0x0f, 0x95, 0xd5, 0xa5, 0xb5, 0x8a, 0x7d, 0xac, 0x1d, 0x58, 0xef,
	0xcb, 0x6d, 0x7a, 0x46, 0x63, 0x9f, 0x96, 0x57, 0x97, 0x34, 0xf6, 0xc3, 0xd6, 0x02, 0x4a, 0x0c,
	0xf8, 0xf1, 0x77, 0x4f, 0x52, 0x44, 0xd2, 0xbb, 0x67, 0x4f, 0xde, 0x2d, 0x05, 0xe6, 0x0b, 0xb8,
	0x2f, 0xf5, 0x7a, 0x79, 0x26, 0xc5, 0x0d, 0x7b, 0x35, 0x67, 0x99, 0x7d, 0x35, 0x76, 0x0b, 0xd2,
	0xb2, 0xb3, 0x64, 0xaf, 0xf6, 0x1d, 0xd4, 0x5e, 0xc4, 0x6f, 0xdf, 0xba, 0x2b, 0xce, 0xff, 0x05,
	0xd4, 0xce, 0xd9, 0x50, 0x7d, 0x06, 0xda, 0x9c, 0x82, 0xcf, 0xc1, 0xb9, 0xfc, 0x1b, 0xb6, 0xae,
	0x40, 0x4b, 0x0c, 0x9f, 0x58, 0xda, 0xfe, 0xe6, 0xd2, 0x9a, 0x62, 0xce, 0x6b, 0xcb, 0x7b, 0x92,
	0x5d, 0x5e, 0x33, 0xf5, 0xad, 0x2e, 0xf1, 0x1f, 0x79, 0x68, 0x64, 0x0c, 0xe4, 0x29, 0x6c, 0x89,
	0x37, 0x47, 0x06, 0x5e, 0xa4, 0xe2, 0x2d, 0x1a, 0xe7, 0xc9, 0xfa, 0x86, 0xf1, 0x02, 0x79, 0xf6,
	0x0c, 0x5d, 0x59, 0x4c, 0x76, 0x2c, 0x3c, 0xa9, 0x65, 0x1a, 0x1c, 0x36, 0xbd, 0x85, 0x7b, 0xea,
	0xf9, 0xd7, 0x78, 0xf6, 0x5a, 0xdc, 0xa7, 0x2a, 0xcf, 0x5e, 0x93, 0x67, 0xb0, 0xad, 0xf2, 0xd8,
	0xfd, 0x23, 0x4a, 0xfa, 0x56, 0xca, 0x34, 0x11, 0x26, 0x2d, 0x68, 0x5c, 0xda, 0x5e, 0x94, 0x7a,
	0xe6, 0x95, 0xbd, 0x86, 0xa0, 0xf4, 0x9b, 0xe5, 0xd8, 0x6b, 0x51, 0xd7, 0x53, 0x8e, 0xbd, 0xc6,
	0x77, 0x4b, 0x39, 0xdc, 0x63, 0x45, 0x54, 0x7f, 0xc1, 0xe2, 0xfe, 0x76, 0xa0, 0xc2, 0x5f, 0x21,
	0x64, 0xc5, 0xbd, 0x44, 0xe5, 0x10, 0x2b, 0x3f, 0xab, 0x66, 0x56, 0x74, 0xb5, 0x74, 0x59, 0x65,
	0xd7, 0xa8, 0xc6, 0x10, 0xf3, 0x6a, 0xe9, 0x62, 0x78, 0xb5, 0x24, 0xad, 0x70, 0x89, 0xec, 0x9a,
	0xe0, 0x97, 0x41, 0x46, 0xa2, 0x6c, 0xa1, 0x81, 0xdd, 0x82, 0x42, 0xa0, 0xfc, 0x3f, 0xbc, 0x9f,
	0x11, 0xde, 0xbf, 0x26, 0xd9, 0xab, 0x48, 0x10, 0x99, 0xbd, 0xa8, 0xa2, 0x85, 0x04, 0x11, 0x99,
	0x2b, 0xb4, 0x34, 0x4a, 0x90, 0xe5, 0x2a, 0x70, 0xe2, 0x59, 0x2a, 0x42, 0xea, 0x7e, 0xbc, 0x18,
	0x4b, 0x4c, 0x92, 0x66, 0x81, 0x1f, 0xc6, 0x0b, 0x24, 0x15, 0x12, 0x52, 0x57, 0x62, 0xa8, 0xae,
	0xc4, 0x2c, 0x96, 0xd2, 0xa8, 0xd4, 0x04, 0x86, 0xab, 0x43, 0x8a, 0x98, 0x83, 0x53, 0x44, 0x1c,
	0x05, 0xc6, 0x28, 0x1f, 0x57, 0xe5, 0xaa, 0xbc, 0xa9, 0x6c, 0xc8, 0x9b, 0x87, 0x00, 0x4c, 0x4f,
	0xf0, 0xa9, 0x85, 0xe8, 0x60, 0x08, 0x9b, 0x38, 0xa3, 0x29, 0xb4, 0xdb, 0x35, 0xc5, 0xbf, 0x73,
	0x6a, 0xe5, 0xba, 0x7e, 0xed, 0xef, 0x67, 0xdb, 0x38, 0xd2, 0x56, 0xc8, 0xd9, 0x6b, 0x5e, 0x0a,
	0x84, 0x82, 0x22, 0x10, 0x6e, 0xbe, 0xfa, 0x7f, 0x73, 0x5b, 0x1f, 0xb7, 0x0d, 0x8d, 0x31, 0x1d,
	0xf5, 0xa6, 0x5d, 0xa3, 0x67, 0x0d, 0x4c, 0xe3, 0x54, 0xcf, 0x21, 0xd4, 0x1d, 0x0d, 0x27, 0xd3,
	0x53, 0x09, 0xb1, 0x36, 0x8e, 0xb3, 0xf0, 0x46, 0x63, 0x18, 0xd3, 0x00, 0x9c, 0x96, 0x60, 0x45,
	0x26, 0x71, 0xf0, 0xae, 0xc1, 0x4b, 0xef, 0xc5, 0xb4, 0xdf, 0x37, 0xa8, 0x5e, 0x22, 0x55, 0x28,
	0x0e, 0x7a, 0x27, 0x86, 0x5e, 0x6e, 0xfd, 0x2d, 0x07, 0xf5, 0xd3, 0xc0, 0x89, 0x43, 0x99, 0x3c,
	0x6a, 0xb4, 0x73, 0x1b, 0xd1, 0x4e, 0x84, 0xf2, 0x85, 0x6b, 0x47, 0x17, 0xae, 0x2f, 0x13, 0x87,
	0x0b, 0xe5, 0x63, 0x01, 0xa6, 0x92, 0x7b, 0xb9, 0x8a, 0x1d, 0x57, 0x26, 0x0e, 0x97, 0xdc, 0x63,
	0x06, 0x91, 0x6f, 0x60, 0x5b, 0x1c, 0x08, 0x6b, 0xb6, 0x0a, 0xc2, 0x90, 0x9d, 0x30, 0x9e, 0x3c,
	0x4d, 0xd6, 0xd1, 0x05, 0x5d, 0x84, 0xf1, 0x90, 0x5d, 0xa7, 0xda, 0x6b, 0x91, 0x44, 0x19, 0xaa,
	0xbd, 0x6e, 0xfd, 0x27, 0x07, 0xc0, 0x16, 0x73, 0xf3, 0x2e, 0x7e, 0x9d, 0xdd, 0xc5, 0xed, 0x76,
	0xca, 0xfd, 0xe4, 0x26, 0xb6, 0xfe, 0x98, 0xbb, 0x5d, 0xa9, 0x0d, 0x8d, 0xa9, 0x49, 0x3b, 0x27,
	0x7c, 0xa3, 0x8e, 0x8d, 0x8e, 0x79, 0x6c, 0x0c, 0x27, 0x16, 0x9d, 0x32, 0x8d, 0xb9, 0x05, 0xb5,
	0x31, 0x9d, 0xf6, 0x0c, 0x01, 0x14, 0x50, 0x89, 0x98, 0xb4, 0x33, 0x9c, 0x0c, 0xf0, 0xf2, 0xb7,
	0xcc, 0x91, 0x25, 0x9f, 0xd0, 0x8b, 0x64, 0x07, 0xee, 0x66, 0x6d, 0xfc, 0x51, 0xbd, 0x84, 0xca,
	0x56, 0xea, 0x17, 0x73, 0x64, 0x75, 0xe9, 0x68, 0x32, 0xd1, 0xcb, 0xd8, 0xa0, 0xb3, 0xbf, 0x28,
	0x0d, 0x2b, 0xad, 0xdf, 0x17, 0xa0, 0x31, 0xf5, 0xbd, 0xd0, 0x5d, 0x7f, 0xce, 0x6e, 0x3e, 0x57,
	0xfa, 0x0c, 0x1e, 0x91, 0x07, 0xed, 0xcc, 0xd3, 0x37, 0xf5, 0x1a, 0x5f, 0x80, 0x86, 0x55, 0x61,
	0x61, 0xcf, 0x93, 0x8d, 0xad, 0xfa, 0xf1, 0xe2, 0x14, 0xc7, 0xb2, 0xb5, 0x79, 0xeb, 0x72, 0x73,
	0x31, 0x69, 0x6d, 0xfa, 0x1c, 0x41, 0x02, 0xf6, 0x8c, 0xf6, 0x7c, 0x1e, 0x5c, 0xba, 0x0e, 0xdb,
	0xc5, 0x12, 0xc5, 0x2e, 0xb3, 0xc3, 0x11, 0x9c, 0x1e, 0x99, 0xfc, 0x38, 0xf3, 0x4a, 0x50, 0x45,
	0x80, 0x9d, 0xe6, 0x47, 0x50, 0xe3, 0x53, 0x73, 0x33, 0xaf, 0x05, 0xc0, 0x21, 0x59, 0x6a, 0x56,
	0xa8, 0x11, 0x56, 0x91, 0x5a, 0x0f, 0x6a, 0x02, 0xbb, 0x5e, 0x6a, 0xb4, 0x8f, 0x7e, 0x00, 0xf8,
	0x48, 0x0f, 0xf2, 0x5c, 0xe9, 0x41, 0x36, 0xd2, 0x41, 0x83, 0x12, 0xeb, 0x40, 0xf4, 0x1c, 0x5a,
	0x92, 0xb6, 0x43, 0xcf, 0xb7, 0x7e, 0xc8, 0x43, 0x8d, 0xc7, 0xf7, 0x33, 0x8b, 0x8c, 0x42, 0xfe,
	0x74, 0x7e, 0xfe, 0xf9, 0x23, 0xf9, 0xf9, 0x6a, 0x6a, 0x4c, 0x79, 0x27, 0x51, 0x87, 0x2a, 0x53,
	0xd4, 0xbc, 0x95, 0xa8, 0x41, 0x05, 0x75, 0x34, 0x0e, 0x0a, 0x44, 0x87, 0xba, 0x50, 0xbb, 0x5c,
	0xde, 0xb3, 0xf6, 0xe1, 0xb4, 0x73, 0x22, 0xf5, 0xb5, 0x35, 0x1a, 0xea, 0x25, 0x2c, 0x27, 0x19,
	0xac, 0xdf, 0xd7, 0xcb, 0xac, 0xeb, 0x32, 0x36, 0xa8, 0xac, 0x69, 0xd8, 0x40, 0xfb, 0x7d, 0xbd,
	0x8a, 0x22, 0x31, 0x5d, 0x18, 0x13, 0x89, 0x31, 0x1b, 0x66, 0x45, 0x22, 0xa7, 0x30, 0x91, 0x18,
	0xcb, 0xbf, 0x4c, 0x24, 0x26, 0x86, 0x1f, 0x2f, 0x12, 0x33, 0xc9, 0xfd, 0x11, 0x91, 0x98, 0xb8,
	0x50, 0x45, 0xe2, 0x9f, 0xf2, 0xf2, 0x6c, 0x49, 0x25, 0x73, 0xfd, 0x5b, 0x1f, 0xab, 0x47, 0x56,
	0x1c, 0x7a, 0xfe, 0x3b, 0x45, 0xac, 0xb0, 0x4f, 0x54, 0x53, 0x04, 0xb1, 0x9c, 0x6d, 0xb0, 0x12,
	0xa9, 0xa2, 0xb0, 0xec, 0x35, 0xd9, 0x07, 0x5d, 0x61, 0x71, 0xd9, 0xa0, 0xd4, 0x3c, 0xc6, 0xe3,
	0xba, 0xe1, 0x21, 0xb0, 0xef, 0x5b, 0xa1, 0x15, 0x87, 0xae, 0x23, 0x2f, 0x4f, 0x86, 0x4c, 0x43,
	0xd7, 0xb9, 0x2e, 0x63, 0xaa, 0x9f, 0x21, 0x63, 0xb4, 0xcf, 0x92, 0x31, 0xb5, 0x1b, 0x64, 0x4c,
	0xab, 0x02, 0x25, 0x63, 0xb1, 0x8c, 0xae, 0x5a, 0x5f, 0x43, 0x55, 0x1e, 0x1c, 0x3c, 0xd5, 0xe9,
	0xb1, 0xca, 0xb1, 0x4b, 0x30, 0x3d, 0x4b, 0x87, 0xb0, 0x2b, 0x89, 0xaf, 0xed, 0xb9, 0xe7, 0xb0,
	0x93, 0x48, 0xdd, 0x70, 0x19, 0xf8, 0x21, 0xbb, 0x3b, 0x3f, 0x20, 0xca, 0x1e, 0xab, 0x52, 0x3e,
	0x38, 0xfc, 0x4b, 0x01, 0x0a, 0xdd, 0xc9, 0x84, 0x3c, 0x85, 0xfa, 0x58, 0x7e, 0xd6, 0x42, 0x61,
	0xa3, 0x7c, 0x5f, 0xdb, 0xad, 0xca, 0x6f, 0xad, 0xdf, 0xe6, 0xc8, 0x63, 0x80, 0x23, 0x37, 0x92,
	0x7d, 0x4c, 0x7a, 0xa4, 0x13, 0x12, 0xca, 0x1d, 0x8d, 0x4a, 0xf9, 0x49, 0x94, 0x5e, 0x69, 0xb7,
	0x2a, 0xfb, 0xf9, 0x64, 0x1e, 0xd9, 0xaa, 0x65, 0xe6, 0x91, 0xe0, 0x01, 0x34, 0x5e, 0x04, 0xb1,
	0xef, 0xb8, 0x0e, 0xd7, 0x08, 0x64, 0xa3, 0x39, 0xd9, 0xad, 0xab, 0xe2, 0xe1, 0xdb, 0x1c, 0xf9,
	0x06, 0x9a, 0x47, 0x6e, 0xa4, 0xf6, 0x4d, 0xca, 0xbc, 0x2a, 0x39, 0x24, 0xfb, 0x50, 0xe6, 0x29,
	0x48, 0x36, 0x92, 0x79, 0xb7, 0xae, 0x16, 0x8b, 0x64, 0x52, 0xf5, 0x9c, 0x65, 0x26, 0x55, 0x0d,
	0x7b, 0x50, 0x1b, 0xba, 0x97, 0xc9, 0x5e, 0x95, 0xdb, 0x6c, 0xff, 0x76, 0x53, 0x3e, 0xf9, 0x0e,
	0x74, 0xb1, 0x33, 0x6e, 0x82, 0x29, 0xd3, 0x7d, 0xd1, 0xbe, 0x7d, 0xff, 0x5e, 0xec, 0xff, 0xea,
	0xe9, 0x3b, 0x2f, 0x9a, 0xdb, 0xe7, 0xed, 0x59, 0xb0, 0x38, 0xb0, 0x1d, 0x7b, 0x71, 0x65, 0xbf,
	0x77, 0xc3, 0x83, 0x99, 0xbd, 0x0c, 0xa3, 0xc0, 0x77, 0x0f, 0xde, 0xad, 0x96, 0xb3, 0x83, 0x59,
	0x18, 0x9e, 0x97, 0xd9, 0xd7, 0xf4, 0xe7, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x09, 0xe7,
	0x9e, 0x5a, 0x17, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CSSClient is the client API for CSS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CSSClient interface {
	Philosophize(ctx context.Context, in *DPOptions, opts ...grpc.CallOption) (CSS_PhilosophizeClient, error)
	GetDPStats(ctx context.Context, in *SaveCode, opts ...grpc.CallOption) (*DPStats, error)
	ReadWrite(ctx context.Context, in *RWOptions, opts ...grpc.CallOption) (CSS_ReadWriteClient, error)
	GetRWStats(ctx context.Context, in *SaveCode, opts ...grpc.CallOption) (*RWStats, error)
	BoundedBuffer(ctx context.Context, in *BufferOptions, opts ...grpc.CallOption) (CSS_BoundedBufferClient, error)
	GetBufferStats(ctx context.Context, in *SaveCode, opts ...grpc.CallOption) (*BufferStats, error)
	Unisex(ctx context.Context, in *UnisexOptions, opts ...grpc.CallOption) (CSS_UnisexClient, error)
	GetUnisexStats(ctx context.Context, in *SaveCode, opts ...grpc.CallOption) (*UnisexStats, error)
	NewSaveCode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SaveCode, error)
	ValidateSaveCode(ctx context.Context, in *SaveCode, opts ...grpc.CallOption) (*SaveCodeValidationResponse, error)
}

type cSSClient struct {
	cc grpc.ClientConnInterface
}

func NewCSSClient(cc grpc.ClientConnInterface) CSSClient {
	return &cSSClient{cc}
}

func (c *cSSClient) Philosophize(ctx context.Context, in *DPOptions, opts ...grpc.CallOption) (CSS_PhilosophizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CSS_serviceDesc.Streams[0], "/CSS/Philosophize", opts...)
	if err != nil {
		return nil, err
	}
	x := &cSSPhilosophizeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CSS_PhilosophizeClient interface {
	Recv() (*DPState, error)
	grpc.ClientStream
}

type cSSPhilosophizeClient struct {
	grpc.ClientStream
}

func (x *cSSPhilosophizeClient) Recv() (*DPState, error) {
	m := new(DPState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cSSClient) GetDPStats(ctx context.Context, in *SaveCode, opts ...grpc.CallOption) (*DPStats, error) {
	out := new(DPStats)
	err := c.cc.Invoke(ctx, "/CSS/GetDPStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cSSClient) ReadWrite(ctx context.Context, in *RWOptions, opts ...grpc.CallOption) (CSS_ReadWriteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CSS_serviceDesc.Streams[1], "/CSS/ReadWrite", opts...)
	if err != nil {
		return nil, err
	}
	x := &cSSReadWriteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CSS_ReadWriteClient interface {
	Recv() (*RWState, error)
	grpc.ClientStream
}

type cSSReadWriteClient struct {
	grpc.ClientStream
}

func (x *cSSReadWriteClient) Recv() (*RWState, error) {
	m := new(RWState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cSSClient) GetRWStats(ctx context.Context, in *SaveCode, opts ...grpc.CallOption) (*RWStats, error) {
	out := new(RWStats)
	err := c.cc.Invoke(ctx, "/CSS/GetRWStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cSSClient) BoundedBuffer(ctx context.Context, in *BufferOptions, opts ...grpc.CallOption) (CSS_BoundedBufferClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CSS_serviceDesc.Streams[2], "/CSS/BoundedBuffer", opts...)
	if err != nil {
		return nil, err
	}
	x := &cSSBoundedBufferClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CSS_BoundedBufferClient interface {
	Recv() (*BufferState, error)
	grpc.ClientStream
}

type cSSBoundedBufferClient struct {
	grpc.ClientStream
}

func (x *cSSBoundedBufferClient) Recv() (*BufferState, error) {
	m := new(BufferState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cSSClient) GetBufferStats(ctx context.Context, in *SaveCode, opts ...grpc.CallOption) (*BufferStats, error) {
	out := new(BufferStats)
	err := c.cc.Invoke(ctx, "/CSS/GetBufferStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cSSClient) Unisex(ctx context.Context, in *UnisexOptions, opts ...grpc.CallOption) (CSS_UnisexClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CSS_serviceDesc.Streams[3], "/CSS/Unisex", opts...)
	if err != nil {
		return nil, err
	}
	x := &cSSUnisexClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CSS_UnisexClient interface {
	Recv() (*UnisexState, error)
	grpc.ClientStream
}

type cSSUnisexClient struct {
	grpc.ClientStream
}

func (x *cSSUnisexClient) Recv() (*UnisexState, error) {
	m := new(UnisexState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cSSClient) GetUnisexStats(ctx context.Context, in *SaveCode, opts ...grpc.CallOption) (*UnisexStats, error) {
	out := new(UnisexStats)
	err := c.cc.Invoke(ctx, "/CSS/GetUnisexStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cSSClient) NewSaveCode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SaveCode, error) {
	out := new(SaveCode)
	err := c.cc.Invoke(ctx, "/CSS/NewSaveCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cSSClient) ValidateSaveCode(ctx context.Context, in *SaveCode, opts ...grpc.CallOption) (*SaveCodeValidationResponse, error) {
	out := new(SaveCodeValidationResponse)
	err := c.cc.Invoke(ctx, "/CSS/ValidateSaveCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CSSServer is the server API for CSS service.
type CSSServer interface {
	Philosophize(*DPOptions, CSS_PhilosophizeServer) error
	GetDPStats(context.Context, *SaveCode) (*DPStats, error)
	ReadWrite(*RWOptions, CSS_ReadWriteServer) error
	GetRWStats(context.Context, *SaveCode) (*RWStats, error)
	BoundedBuffer(*BufferOptions, CSS_BoundedBufferServer) error
	GetBufferStats(context.Context, *SaveCode) (*BufferStats, error)
	Unisex(*UnisexOptions, CSS_UnisexServer) error
	GetUnisexStats(context.Context, *SaveCode) (*UnisexStats, error)
	NewSaveCode(context.Context, *Empty) (*SaveCode, error)
	ValidateSaveCode(context.Context, *SaveCode) (*SaveCodeValidationResponse, error)
}

// UnimplementedCSSServer can be embedded to have forward compatible implementations.
type UnimplementedCSSServer struct {
}

func (*UnimplementedCSSServer) Philosophize(req *DPOptions, srv CSS_PhilosophizeServer) error {
	return status.Errorf(codes.Unimplemented, "method Philosophize not implemented")
}
func (*UnimplementedCSSServer) GetDPStats(ctx context.Context, req *SaveCode) (*DPStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDPStats not implemented")
}
func (*UnimplementedCSSServer) ReadWrite(req *RWOptions, srv CSS_ReadWriteServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadWrite not implemented")
}
func (*UnimplementedCSSServer) GetRWStats(ctx context.Context, req *SaveCode) (*RWStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRWStats not implemented")
}
func (*UnimplementedCSSServer) BoundedBuffer(req *BufferOptions, srv CSS_BoundedBufferServer) error {
	return status.Errorf(codes.Unimplemented, "method BoundedBuffer not implemented")
}
func (*UnimplementedCSSServer) GetBufferStats(ctx context.Context, req *SaveCode) (*BufferStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBufferStats not implemented")
}
func (*UnimplementedCSSServer) Unisex(req *UnisexOptions, srv CSS_UnisexServer) error {
	return status.Errorf(codes.Unimplemented, "method Unisex not implemented")
}
func (*UnimplementedCSSServer) GetUnisexStats(ctx context.Context, req *SaveCode) (*UnisexStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnisexStats not implemented")
}
func (*UnimplementedCSSServer) NewSaveCode(ctx context.Context, req *Empty) (*SaveCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewSaveCode not implemented")
}
func (*UnimplementedCSSServer) ValidateSaveCode(ctx context.Context, req *SaveCode) (*SaveCodeValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSaveCode not implemented")
}

func RegisterCSSServer(s *grpc.Server, srv CSSServer) {
	s.RegisterService(&_CSS_serviceDesc, srv)
}

func _CSS_Philosophize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DPOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CSSServer).Philosophize(m, &cSSPhilosophizeServer{stream})
}

type CSS_PhilosophizeServer interface {
	Send(*DPState) error
	grpc.ServerStream
}

type cSSPhilosophizeServer struct {
	grpc.ServerStream
}

func (x *cSSPhilosophizeServer) Send(m *DPState) error {
	return x.ServerStream.SendMsg(m)
}

func _CSS_GetDPStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSSServer).GetDPStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSS/GetDPStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSSServer).GetDPStats(ctx, req.(*SaveCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _CSS_ReadWrite_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RWOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CSSServer).ReadWrite(m, &cSSReadWriteServer{stream})
}

type CSS_ReadWriteServer interface {
	Send(*RWState) error
	grpc.ServerStream
}

type cSSReadWriteServer struct {
	grpc.ServerStream
}

func (x *cSSReadWriteServer) Send(m *RWState) error {
	return x.ServerStream.SendMsg(m)
}

func _CSS_GetRWStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSSServer).GetRWStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSS/GetRWStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSSServer).GetRWStats(ctx, req.(*SaveCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _CSS_BoundedBuffer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BufferOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CSSServer).BoundedBuffer(m, &cSSBoundedBufferServer{stream})
}

type CSS_BoundedBufferServer interface {
	Send(*BufferState) error
	grpc.ServerStream
}

type cSSBoundedBufferServer struct {
	grpc.ServerStream
}

func (x *cSSBoundedBufferServer) Send(m *BufferState) error {
	return x.ServerStream.SendMsg(m)
}

func _CSS_GetBufferStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSSServer).GetBufferStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSS/GetBufferStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSSServer).GetBufferStats(ctx, req.(*SaveCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _CSS_Unisex_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UnisexOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CSSServer).Unisex(m, &cSSUnisexServer{stream})
}

type CSS_UnisexServer interface {
	Send(*UnisexState) error
	grpc.ServerStream
}

type cSSUnisexServer struct {
	grpc.ServerStream
}

func (x *cSSUnisexServer) Send(m *UnisexState) error {
	return x.ServerStream.SendMsg(m)
}

func _CSS_GetUnisexStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSSServer).GetUnisexStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSS/GetUnisexStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSSServer).GetUnisexStats(ctx, req.(*SaveCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _CSS_NewSaveCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSSServer).NewSaveCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSS/NewSaveCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSSServer).NewSaveCode(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CSS_ValidateSaveCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CSSServer).ValidateSaveCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CSS/ValidateSaveCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CSSServer).ValidateSaveCode(ctx, req.(*SaveCode))
	}
	return interceptor(ctx, in, info, handler)
}

var _CSS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CSS",
	HandlerType: (*CSSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDPStats",
			Handler:    _CSS_GetDPStats_Handler,
		},
		{
			MethodName: "GetRWStats",
			Handler:    _CSS_GetRWStats_Handler,
		},
		{
			MethodName: "GetBufferStats",
			Handler:    _CSS_GetBufferStats_Handler,
		},
		{
			MethodName: "GetUnisexStats",
			Handler:    _CSS_GetUnisexStats_Handler,
		},
		{
			MethodName: "NewSaveCode",
			Handler:    _CSS_NewSaveCode_Handler,
		},
		{
			MethodName: "ValidateSaveCode",
			Handler:    _CSS_ValidateSaveCode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Philosophize",
			Handler:       _CSS_Philosophize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadWrite",
			Handler:       _CSS_ReadWrite_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BoundedBuffer",
			Handler:       _CSS_BoundedBuffer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Unisex",
			Handler:       _CSS_Unisex_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "css.proto",
}
